### ISSUE TITLE
Cannot train the module

### ISSUE THREAD

**Issue by ntelo007** [anilbatra2185/road_connectivity#21]
I run the following command in my terminal and I get the following message:
```
$ set CUDA_VISIBLE_DEVICES=0 & python train_mtl.py --config config.json --dataset deepglobe --model_name "LinkNet34MTL" --exp dg_L34_mtl --multi_scale_pred false
Random Seed:  7
Single Cuda Node is avaiable
Training with dataset => DeepGlobeDataset
****************************************************************************************************
Trainable parameters for Model LinkNet34MTL : 22.004903 M
****************************************************************************************************
...
...
Some numba warnings and runtime warnings
...
...


[>....... 1/1 ............]S:9s492ms|T:0ms|Loss: -0.284238 | VecLoss: 4.207048 | road miou: 28.0047%(18.9634%) | angle miou: 0.2155%

Traceback (most recent call last):
  File "train_mtl.py", line 443, in <module>
    main()
  File "train_mtl.py", line 434, in main
    train(epoch)
  File "train_mtl.py", line 294, in train
    write=True,
  File "C:\Users\...\road_connectivity-master\utils\util.py", line 147, in performMetrics
    100 * fwavacc,
TypeError: a bytes-like object is required, not 'str'
```

Do you know how to solve this issue?

**Comment by anilbatra2185** [comment]
It is PyTorch Version issue and request you to use 0.3 version. I hope you might have solved it and if not then request you to please re-open it.
