### ISSUE TITLE
add: Assertion `pos >= 0 && pos < buffer.size()` failed

### ISSUE THREAD

**Issue by isarsy** [anilbatra2185/road_connectivity#35]
Thanks for your fantastic work!When I tried to train this model,I meet this problem:
Traceback (most recent call last):
  File "train_mtl.py", line 427, in <module>
    train(epoch)
  File "train_mtl.py", line 264, in train
    torch.autograd.backward([loss1, loss2])
  File "/home/sy/anaconda3/envs/connect/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: torch/csrc/autograd/input_buffer.cpp:14: add: Assertion `pos >= 0 && pos < buffer.size()` failed.
Hope you can give me some instruction to solve this problem.

**Comment by isarsy** [comment]
I've solved this problem, which resulted from the version of pytorch. When I changed the environment to pytorch0.4.1 and python3.7,this problem disappeared.
